-- tbl_memo TABLE

CREATE TABLE tbl_memo (
	MNO BIGINT NOT NULL AUTO_INCREMENT,
	MEMO_TEXT VARCHAR(200) NOT NULL,
	PRIMARY KEY(MNO)
) ENGINE=INNODB

-- guestbook TABLE

CREATE TABLE guestbook(
	GNO BIGINT NOT NULL AUTO_INCREMENT,
	MODDATE DATETIME(6),
	REGDATE DATETIME(6),
	CONTENT VARCHAR(1500) NOT NULL,
	TITLE VARCHAR(100) NOT NULL,
	WRITER VARCHAR(50) NOT NULL,
	PRIMARY KEY (GNO)
) ENGINE=INNODB



-- board TABLE
CREATE TABLE board(
	BNO BIGINT NOT NULL AUTO_INCREMENT,
	MODDATE DATETIME(6),
	REGDATE DATETIME(6),
	CONTENT VARCHAR(255),
	TITLE VARCHAR(255),
	WRITER_EMAIL VARCHAR(255),
	PRIMARY KEY(BNO)
) ENGINE = INNODB

-- MEMBER TABLE
CREATE TABLE member(
	EMAIL VARCHAR(255) NOT NULL,
	MODDATE DATETIME(6),
	REGDATE DATETIME(6),
	NAME VARCHAR(255),
	PASSWORD VARCHAR(255),
	PRIMARY KEY(EMAIL)
) ENGINE = INNODB

-- REPLY TABLE
CREATE TABLE reply (
	RNO BIGINT NOT NULL AUTO_INCREMENT,
	MODDATE DATETIME(6),
	REGDATE DATETIME(6),
	REPLYER VARCHAR(255),
	TEXT VARCHAR(255),
	BOARD_BNO BIGINT,
	PRIMARY KEY(RNO)
) ENGINE = INNODB

-- FORIEGN KEY APPLY TO BOARD / REPLY
ALTER TABLE board
	ADD CONTRAINT --자동으로 생성되는 외래키의 이름
	FOREIGN KEY (WRITER_EMAIL)
	REFERENCES member(EMAIL)
	
ALTER TABLE reply
	ADD CONTRAINT -- 자동으로 생성되는 외래키의 이름
	FOREIGN KEY (BOARD_BNO)
	REFERENCES board(BNO)	
